// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectRiddle.Infrastructure.Persistence;

#nullable disable

namespace ProjectRiddle.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProjectRiddleDbContext))]
    [Migration("20260821080031_AddUsersAndRiddles")]
    internal sealed partial class AddUsersAndRiddles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ProjectRiddle.Core.Models.Riddles.Riddle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerPattern")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Clue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("SofiaPublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SofiaPublicationDate")
                        .IsUnique()
                        .HasFilter("SofiaPublicationDate IS NOT NULL AND PublicationState IN ('Scheduled', 'Published')");

                    b.ToTable("Riddles", (string)null);
                });

            modelBuilder.Entity("ProjectRiddle.Core.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ProjectRiddle.Core.Models.Riddles.Riddle", b =>
                {
                    b.OwnsMany("ProjectRiddle.Core.Models.Riddles.RiddleRange", "Ranges", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<int>("End")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("RiddleId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Start")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("RiddleId");

                            b1.ToTable("RiddleRanges", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RiddleId");
                        });

                    b.Navigation("Ranges");
                });
#pragma warning restore 612, 618
        }
    }
}
